#include "pch.h"
#include "PrismaUI_API.h"
#include "SKSEMenuFramework.h"

using namespace std::chrono_literals;

namespace
{
    constexpr auto kStonePlugin = "HE Elden Rim - Ash Rings.esp";
    constexpr auto kViewPath = "HE_TechniqueHUD/index.html";
    constexpr auto kDefaultIniRelativePath = "Data\\SKSE\\Plugins\\HE_TechniqueHUD.ini";
    constexpr auto kUserIniRelativePath = "Data\\SKSE\\Plugins\\HE_TechniqueHUD.user.ini";

    constexpr RE::FormID kTechniqueChargesGlobalLocalID = 0xE23;
    constexpr RE::FormID kTechniqueMaxChargesGlobalLocalID = 0xE24;
    constexpr RE::FormID kTechniqueRechargeProgressGlobalLocalID = 0xE25;
    constexpr RE::FormID kTechniqueRecoveryGlobalLocalID = 0xE26;

    PRISMA_UI_API::IVPrismaUI1* g_prisma = nullptr;
    PrismaView g_view = 0;
    std::atomic_bool g_domReady{ false };
    std::jthread g_pollThread;

    RE::TESGlobal* g_currentCharges = nullptr;
    RE::TESGlobal* g_maxCharges = nullptr;
    RE::TESGlobal* g_rechargeProgress = nullptr;
    RE::TESGlobal* g_recoveryPercent = nullptr;

    std::filesystem::path g_defaultIniPath{ kDefaultIniRelativePath };
    std::filesystem::path g_userIniPath{ kUserIniRelativePath };

    struct Config
    {
        int left = 22;
        int bottom = 112;
        int scale = 100;
        int pollMs = 50;
    } g_config;

    struct HUDState
    {
        float current = 0.0f;
        float max = 0.0f;
        float progress = 0.0f;
        float recovery = 0.0f;
    };

    HUDState g_lastState{};
    bool g_hasLastState = false;
    bool g_menuFrameworkRegistered = false;

    std::string Trim(std::string a_value)
    {
        const auto first = a_value.find_first_not_of(" \t\r\n");
        if (first == std::string::npos) {
            return {};
        }
        const auto last = a_value.find_last_not_of(" \t\r\n");
        return a_value.substr(first, last - first + 1);
    }

    void ClampConfig()
    {
        g_config.left = std::clamp(g_config.left, 0, 4000);
        g_config.bottom = std::clamp(g_config.bottom, 0, 4000);
        g_config.scale = std::clamp(g_config.scale, 50, 250);
        g_config.pollMs = std::clamp(g_config.pollMs, 33, 250);
    }

    void ApplyIniFile(const std::filesystem::path& a_path)
    {
        std::ifstream input(a_path);
        if (!input.is_open()) {
            return;
        }

        bool inHudSection = false;
        std::string line;
        while (std::getline(input, line)) {
            line = Trim(line);
            if (line.empty() || line.starts_with(';') || line.starts_with('#')) {
                continue;
            }

            if (line.front() == '[' && line.back() == ']') {
                inHudSection = (Trim(line.substr(1, line.size() - 2)) == "HUD");
                continue;
            }
            if (!inHudSection) {
                continue;
            }

            const auto eq = line.find('=');
            if (eq == std::string::npos) {
                continue;
            }

            const auto key = Trim(line.substr(0, eq));
            const auto value = Trim(line.substr(eq + 1));

            try {
                const int number = std::stoi(value);
                if (key == "Left") {
                    g_config.left = number;
                } else if (key == "Bottom") {
                    g_config.bottom = number;
                } else if (key == "Scale") {
                    g_config.scale = number;
                } else if (key == "PollMs") {
                    g_config.pollMs = number;
                }
            } catch (...) {
                SKSE::log::warn("Ignoring invalid HUD setting {}={} from {}", key, value, a_path.string());
            }
        }
    }

    void LoadConfig()
    {
        g_config = {};
        ApplyIniFile(g_defaultIniPath);
        ApplyIniFile(g_userIniPath);
        ClampConfig();

        SKSE::log::info(
            "Loaded charge HUD layout Left={} Bottom={} Scale={}%; user config={}",
            g_config.left,
            g_config.bottom,
            g_config.scale,
            std::filesystem::absolute(g_userIniPath).string());
    }

    bool SaveLayoutConfig()
    {
        ClampConfig();

        std::error_code ec;
        std::filesystem::create_directories(g_userIniPath.parent_path(), ec);
        if (ec) {
            SKSE::log::error(
                "Could not create HUD user config directory {}: {}",
                g_userIniPath.parent_path().string(),
                ec.message());
            return false;
        }

        std::ofstream output(g_userIniPath, std::ios::out | std::ios::trunc);
        if (!output.is_open()) {
            SKSE::log::error(
                "Could not open HUD user config for writing: {}",
                std::filesystem::absolute(g_userIniPath).string());
            return false;
        }

        output
            << "[HUD]\n"
            << "; Auto-generated by HE Technique HUD.\n"
            << "; Under MO2 this file should appear in Overwrite\\SKSE\\Plugins.\n"
            << "Left=" << g_config.left << "\n"
            << "Bottom=" << g_config.bottom << "\n"
            << "Scale=" << g_config.scale << "\n"
            << "PollMs=" << g_config.pollMs << "\n";
        output.flush();

        if (!output.good()) {
            SKSE::log::error(
                "Failed while writing HUD user config: {}",
                std::filesystem::absolute(g_userIniPath).string());
            return false;
        }

        SKSE::log::info(
            "Saved HUD settings Left={} Bottom={} Scale={}% to {}",
            g_config.left,
            g_config.bottom,
            g_config.scale,
            std::filesystem::absolute(g_userIniPath).string());
        return true;
    }

    void ApplyLayoutToHUD()
    {
        if (!g_prisma || !g_domReady.load() || !g_view || !g_prisma->IsValid(g_view)) {
            return;
        }

        const auto script = std::format(
            "window.TechniqueHUD&&window.TechniqueHUD.setLayout({},{},{});",
            g_config.left,
            g_config.bottom,
            g_config.scale);
        g_prisma->Invoke(g_view, script.c_str());
    }

    void ResolveForms()
    {
        auto* dataHandler = RE::TESDataHandler::GetSingleton();
        if (!dataHandler) {
            SKSE::log::error("TESDataHandler unavailable");
            return;
        }

        g_currentCharges = dataHandler->LookupForm<RE::TESGlobal>(kTechniqueChargesGlobalLocalID, kStonePlugin);
        g_maxCharges = dataHandler->LookupForm<RE::TESGlobal>(kTechniqueMaxChargesGlobalLocalID, kStonePlugin);
        g_rechargeProgress = dataHandler->LookupForm<RE::TESGlobal>(kTechniqueRechargeProgressGlobalLocalID, kStonePlugin);
        g_recoveryPercent = dataHandler->LookupForm<RE::TESGlobal>(kTechniqueRecoveryGlobalLocalID, kStonePlugin);

        SKSE::log::info(
            "Technique Charge globals: current={} max={} progress={} recovery={}",
            g_currentCharges ? "OK" : "MISSING",
            g_maxCharges ? "OK" : "MISSING",
            g_rechargeProgress ? "OK" : "MISSING",
            g_recoveryPercent ? "OK" : "MISSING");
    }

    bool MeaningfullyChanged(const HUDState& a_state)
    {
        if (!g_hasLastState) {
            return true;
        }

        return std::fabs(a_state.current - g_lastState.current) >= 0.001f ||
               std::fabs(a_state.max - g_lastState.max) >= 0.001f ||
               std::fabs(a_state.progress - g_lastState.progress) >= 0.0025f ||
               std::fabs(a_state.recovery - g_lastState.recovery) >= 0.01f;
    }

    void PushState(const HUDState& a_state)
    {
        if (!g_prisma || !g_domReady.load() || !g_view || !g_prisma->IsValid(g_view) || !MeaningfullyChanged(a_state)) {
            return;
        }

        const auto script = std::format(
            "window.TechniqueHUD&&window.TechniqueHUD.setState({{current:{:.3f},max:{:.3f},progress:{:.5f},recovery:{:.3f}}});",
            a_state.current,
            a_state.max,
            a_state.progress,
            a_state.recovery);

        g_prisma->Invoke(g_view, script.c_str());
        g_lastState = a_state;
        g_hasLastState = true;
    }

    void UpdateHUDOnGameThread()
    {
        if (!g_currentCharges || !g_maxCharges || !g_rechargeProgress || !g_recoveryPercent) {
            return;
        }

        HUDState state{};
        state.current = std::clamp(g_currentCharges->value, 0.0f, 5.0f);
        state.max = std::clamp(g_maxCharges->value, 0.0f, 5.0f);
        state.progress = std::clamp(g_rechargeProgress->value, 0.0f, 1.0f);
        state.recovery = std::clamp(g_recoveryPercent->value, 0.0f, 95.0f);
        PushState(state);
    }

    void StartPolling()
    {
        if (g_pollThread.joinable()) {
            return;
        }

        g_pollThread = std::jthread([](std::stop_token stopToken) {
            while (!stopToken.stop_requested()) {
                if (auto* taskInterface = SKSE::GetTaskInterface()) {
                    taskInterface->AddTask([]() { UpdateHUDOnGameThread(); });
                }
                std::this_thread::sleep_for(std::chrono::milliseconds(g_config.pollMs));
            }
        });
    }

    void CommitMenuChange()
    {
        ClampConfig();
        ApplyLayoutToHUD();
        SaveLayoutConfig();
    }

    void __stdcall RenderMenuFrameworkSettings()
    {
        ImGuiMCP::TextWrapped(
            "Technique Charges HUD placement. Changes apply immediately and save automatically.");

        ImGuiMCP::Spacing();
        bool changed = false;

        ImGuiMCP::SetNextItemWidth(360.0f);
        changed |= ImGuiMCP::SliderInt("Horizontal position", &g_config.left, 0, 3840, "%d px");

        ImGuiMCP::SetNextItemWidth(360.0f);
        changed |= ImGuiMCP::SliderInt("Vertical position", &g_config.bottom, 0, 2160, "%d px");

        ImGuiMCP::SetNextItemWidth(360.0f);
        changed |= ImGuiMCP::SliderInt("HUD scale", &g_config.scale, 50, 250, "%d%%");

        if (changed) {
            CommitMenuChange();
        }

        ImGuiMCP::Spacing();
        if (ImGuiMCP::Button("Reset HUD placement")) {
            g_config.left = 22;
            g_config.bottom = 112;
            g_config.scale = 100;
            CommitMenuChange();
        }

        ImGuiMCP::Separator();
        if (g_currentCharges && g_maxCharges && g_rechargeProgress) {
            const int current = std::clamp(static_cast<int>(std::lround(g_currentCharges->value)), 0, 5);
            const int maximum = std::clamp(static_cast<int>(std::lround(g_maxCharges->value)), 0, 5);
            const int progress = std::clamp(static_cast<int>(std::lround(g_rechargeProgress->value * 100.0f)), 0, 100);
            ImGuiMCP::Text("Current charges: %d / %d", current, maximum);
            if (current < maximum) {
                ImGuiMCP::Text("Next charge: %d%%", progress);
            }
        }

        ImGuiMCP::Spacing();
        ImGuiMCP::TextWrapped(
            "Saved to Data\\SKSE\\Plugins\\HE_TechniqueHUD.user.ini. "
            "With Mod Organizer 2 this newly-created file should be written to Overwrite.");
    }

    void RegisterMenuFramework()
    {
        if (g_menuFrameworkRegistered) {
            return;
        }

        if (!SKSEMenuFramework::IsInstalled()) {
            SKSE::log::warn(
                "SKSE Menu Framework not installed; charge HUD will work but its settings page is unavailable.");
            return;
        }

        SKSEMenuFramework::SetSection("HE Technique HUD");
        SKSEMenuFramework::AddSectionItem("HUD Settings", RenderMenuFrameworkSettings);
        g_menuFrameworkRegistered = true;

        SKSE::log::info(
            "Registered HE Technique HUD settings with SKSE Menu Framework v{:.2f}",
            SKSEMenuFramework::GetMenuFrameworkVersion());
    }

    void CreateHUDView()
    {
        g_prisma = PRISMA_UI_API::RequestPluginAPI<PRISMA_UI_API::IVPrismaUI1>();
        if (!g_prisma) {
            SKSE::log::error("PrismaUI API unavailable");
            return;
        }

        g_view = g_prisma->CreateView(kViewPath, [](PrismaView a_view) {
            g_view = a_view;
            g_domReady.store(true);
            ApplyLayoutToHUD();
            g_prisma->SetOrder(g_view, 500);
            g_prisma->Show(g_view);
            SKSE::log::info("Technique Charge HUD DOM ready");
        });

        if (!g_view || !g_prisma->IsValid(g_view)) {
            SKSE::log::error("PrismaUI CreateView failed for {}", kViewPath);
            g_view = 0;
        }
    }

    void MessageHandler(SKSE::MessagingInterface::Message* a_message)
    {
        if (!a_message) {
            return;
        }

        switch (a_message->type) {
        case SKSE::MessagingInterface::kDataLoaded:
            LoadConfig();
            ResolveForms();
            CreateHUDView();
            RegisterMenuFramework();
            StartPolling();
            break;

        case SKSE::MessagingInterface::kPostLoadGame:
        case SKSE::MessagingInterface::kNewGame:
            g_hasLastState = false;
            ApplyLayoutToHUD();
            break;

        default:
            break;
        }
    }
}

SKSEPluginLoad(const SKSE::LoadInterface* a_skse)
{
    if (auto path = SKSE::log::log_directory()) {
        *path /= "HE_TechniqueHUD.log";
        auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
        auto log = std::make_shared<spdlog::logger>("HE_TechniqueHUD", std::move(sink));
        spdlog::set_default_logger(std::move(log));
        spdlog::set_level(spdlog::level::info);
        spdlog::flush_on(spdlog::level::info);
    }

    SKSE::Init(a_skse);

    if (auto* messaging = SKSE::GetMessagingInterface()) {
        messaging->RegisterListener("SKSE", MessageHandler);
    } else {
        return false;
    }

    SKSE::log::info("HE Technique HUD v5.7.8 SKSE Menu Framework settings loaded");
    return true;
}
